version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: server
    main: ./main.go
    binary: server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: migrate
    main: ./cmd/migrate/main.go
    binary: migrate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - .env.example
      - migrations/*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: "Refactoring"
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: yourusername
    name: go-grst-boilerplate
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## What's Changed
  footer: |
    ---
    **Full Changelog**: https://github.com/yourusername/go-grst-boilerplate/compare/{{ .PreviousTag }}...{{ .Tag }}

dockers:
  - image_templates:
      - "ghcr.io/yourusername/go-grst-boilerplate:{{ .Tag }}"
      - "ghcr.io/yourusername/go-grst-boilerplate:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
