// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grst/annotations.proto

// Package grst defines custom protobuf options used by this boilerplate to
// declare a service's HTTP surface directly on each RPC. The protoc-gen-fiber
// plugin reads these options and generates the Go Fiber route registration, so
// the .proto is the single source of truth for method, path, auth, and rate
// limiting — no hand-written route tables.

package grst

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResponseStyle selects how a successful handler result is serialized.
type ResponseStyle int32

const (
	// 200 OK, single message under `data`.
	ResponseStyle_RESPONSE_STYLE_OK ResponseStyle = 0
	// 201 Created, single message under `data`.
	ResponseStyle_RESPONSE_STYLE_CREATED ResponseStyle = 1
	// 200 OK list envelope: the response's single repeated field becomes `data`
	// and its pagination message (if any) becomes `meta`.
	ResponseStyle_RESPONSE_STYLE_LIST ResponseStyle = 2
)

// Enum value maps for ResponseStyle.
var (
	ResponseStyle_name = map[int32]string{
		0: "RESPONSE_STYLE_OK",
		1: "RESPONSE_STYLE_CREATED",
		2: "RESPONSE_STYLE_LIST",
	}
	ResponseStyle_value = map[string]int32{
		"RESPONSE_STYLE_OK":      0,
		"RESPONSE_STYLE_CREATED": 1,
		"RESPONSE_STYLE_LIST":    2,
	}
)

func (x ResponseStyle) Enum() *ResponseStyle {
	p := new(ResponseStyle)
	*p = x
	return p
}

func (x ResponseStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_grst_annotations_proto_enumTypes[0].Descriptor()
}

func (ResponseStyle) Type() protoreflect.EnumType {
	return &file_grst_annotations_proto_enumTypes[0]
}

func (x ResponseStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStyle.Descriptor instead.
func (ResponseStyle) EnumDescriptor() ([]byte, []int) {
	return file_grst_annotations_proto_rawDescGZIP(), []int{0}
}

// Route declares how an RPC is exposed over REST. Attach it to a method:
//
//	rpc GetUser(GetUserReq) returns (UserProfile) {
//	  option (grst.route) = {
//	    method: "GET"
//	    path: "/api/v1/users/{id}"
//	    auth: { required: true, roles: ["admin", "superadmin"] }
//	  };
//	}
//
// Path parameters use {name} and are matched against request fields by
// json_name (converted to Fiber's :name syntax at generation time). For GET
// requests, request fields not bound to a path parameter are populated from
// query-string parameters.
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP verb: GET, POST, PUT, PATCH, or DELETE.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Path template, e.g. "/api/v1/users/{id}". {segments} become path params.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// When true, the JSON request body is parsed into the request message
	// (typically for POST/PUT/PATCH). Ignored for bodyless requests.
	Body bool `protobuf:"varint,3,opt,name=body,proto3" json:"body,omitempty"`
	// Authentication/authorization policy for this route. Absent means public.
	Auth *Auth `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	// How the successful response is written. Defaults to a 200 OK envelope.
	Response ResponseStyle `protobuf:"varint,5,opt,name=response,proto3,enum=grst.ResponseStyle" json:"response,omitempty"`
	// Optional per-route rate limit applied before the handler. Useful for
	// unauthenticated credential endpoints (login/register) to blunt brute force.
	RateLimit     *RateLimit `protobuf:"bytes,6,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_grst_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_grst_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_grst_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Route) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Route) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Route) GetBody() bool {
	if x != nil {
		return x.Body
	}
	return false
}

func (x *Route) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Route) GetResponse() ResponseStyle {
	if x != nil {
		return x.Response
	}
	return ResponseStyle_RESPONSE_STYLE_OK
}

func (x *Route) GetRateLimit() *RateLimit {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

// Auth is the per-route authentication policy.
type Auth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When true, a valid token is required to reach the handler.
	Required bool `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	// If non-empty, the caller must hold at least one of these roles. Implies
	// required = true.
	Roles         []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_grst_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_grst_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_grst_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Auth) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Auth) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// RateLimit configures a fixed-window per-IP limiter for a single route.
type RateLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum requests allowed per window.
	Max uint32 `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	// Window length in seconds.
	WindowSeconds uint32 `protobuf:"varint,2,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_grst_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_grst_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_grst_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *RateLimit) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *RateLimit) GetWindowSeconds() uint32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

var file_grst_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Route)(nil),
		Field:         50123,
		Name:          "grst.route",
		Tag:           "bytes,50123,opt,name=route",
		Filename:      "grst/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// Field number in the internal (50000-99999) extension range.
	//
	// optional grst.Route route = 50123;
	E_Route = &file_grst_annotations_proto_extTypes[0]
)

var File_grst_annotations_proto protoreflect.FileDescriptor

const file_grst_annotations_proto_rawDesc = "" +
	"\n" +
	"\x16grst/annotations.proto\x12\x04grst\x1a google/protobuf/descriptor.proto\"\xc8\x01\n" +
	"\x05Route\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x03 \x01(\bR\x04body\x12\x1e\n" +
	"\x04auth\x18\x04 \x01(\v2\n" +
	".grst.AuthR\x04auth\x12/\n" +
	"\bresponse\x18\x05 \x01(\x0e2\x13.grst.ResponseStyleR\bresponse\x12.\n" +
	"\n" +
	"rate_limit\x18\x06 \x01(\v2\x0f.grst.RateLimitR\trateLimit\"8\n" +
	"\x04Auth\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\bR\brequired\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"D\n" +
	"\tRateLimit\x12\x10\n" +
	"\x03max\x18\x01 \x01(\rR\x03max\x12%\n" +
	"\x0ewindow_seconds\x18\x02 \x01(\rR\rwindowSeconds*[\n" +
	"\rResponseStyle\x12\x15\n" +
	"\x11RESPONSE_STYLE_OK\x10\x00\x12\x1a\n" +
	"\x16RESPONSE_STYLE_CREATED\x10\x01\x12\x17\n" +
	"\x13RESPONSE_STYLE_LIST\x10\x02:C\n" +
	"\x05route\x12\x1e.google.protobuf.MethodOptions\x18ˇ\x03 \x01(\v2\v.grst.RouteR\x05routeB,Z*go-grst-boilerplate/handler/grpc/grst;grstb\x06proto3"

var (
	file_grst_annotations_proto_rawDescOnce sync.Once
	file_grst_annotations_proto_rawDescData []byte
)

func file_grst_annotations_proto_rawDescGZIP() []byte {
	file_grst_annotations_proto_rawDescOnce.Do(func() {
		file_grst_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grst_annotations_proto_rawDesc), len(file_grst_annotations_proto_rawDesc)))
	})
	return file_grst_annotations_proto_rawDescData
}

var file_grst_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grst_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grst_annotations_proto_goTypes = []any{
	(ResponseStyle)(0),                 // 0: grst.ResponseStyle
	(*Route)(nil),                      // 1: grst.Route
	(*Auth)(nil),                       // 2: grst.Auth
	(*RateLimit)(nil),                  // 3: grst.RateLimit
	(*descriptorpb.MethodOptions)(nil), // 4: google.protobuf.MethodOptions
}
var file_grst_annotations_proto_depIdxs = []int32{
	2, // 0: grst.Route.auth:type_name -> grst.Auth
	0, // 1: grst.Route.response:type_name -> grst.ResponseStyle
	3, // 2: grst.Route.rate_limit:type_name -> grst.RateLimit
	4, // 3: grst.route:extendee -> google.protobuf.MethodOptions
	1, // 4: grst.route:type_name -> grst.Route
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	3, // [3:4] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grst_annotations_proto_init() }
func file_grst_annotations_proto_init() {
	if File_grst_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grst_annotations_proto_rawDesc), len(file_grst_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_grst_annotations_proto_goTypes,
		DependencyIndexes: file_grst_annotations_proto_depIdxs,
		EnumInfos:         file_grst_annotations_proto_enumTypes,
		MessageInfos:      file_grst_annotations_proto_msgTypes,
		ExtensionInfos:    file_grst_annotations_proto_extTypes,
	}.Build()
	File_grst_annotations_proto = out.File
	file_grst_annotations_proto_goTypes = nil
	file_grst_annotations_proto_depIdxs = nil
}
