// Package user contains the gRPC user service contract and validation.
//
// Route/auth wiring is no longer hand-maintained here: it is declared via
// veemon.route options in contract/user/user.proto and generated by
// protoc-gen-fiber into user_fiber.pb.go (REST routes + the UserApiAuthConfig
// map used by the gRPC auth interceptor). This file now carries only the
// request validation rules.
package user

import (
	"veemon/pkg/validation"
)

// Request DTOs with validation tags

type RegisterRequest struct {
	Email string `json:"email" validate:"required,email"`
	// max=72: bcrypt ignores bytes beyond 72, so a longer password would be
	// silently truncated. `password`: enforces upper+lower+digit complexity.
	Password string `json:"password" validate:"required,min=8,max=72,password"`
	Name     string `json:"name" validate:"required,min=2,max=100"`
	Phone    string `json:"phone" validate:"omitempty,phone"`
}

type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
}

type ListUsersRequest struct {
	Page      int32  `json:"page" validate:"omitempty,gte=1"`
	Size      int32  `json:"size" validate:"omitempty,gte=1,lte=100"`
	Search    string `json:"search" validate:"omitempty,max=100"`
	SortBy    string `json:"sortBy" validate:"omitempty,oneof=created_at name email"`
	SortOrder string `json:"sortOrder" validate:"omitempty,oneof=asc desc"`
}

type UpdateUserRequest struct {
	Name   string `json:"name" validate:"omitempty,min=2,max=100"`
	Phone  string `json:"phone" validate:"omitempty"`
	Status string `json:"status" validate:"omitempty,oneof=active inactive pending"`
}

// ValidateRequest validates proto request messages using go-playground/validator
func ValidateRequest(req interface{}) error {
	switch r := req.(type) {
	case *RegisterReq:
		validateReq := RegisterRequest{
			Email:    r.Email,
			Password: r.Password,
			Name:     r.Name,
			Phone:    r.Phone,
		}
		return validation.Validate(validateReq)

	case *LoginReq:
		validateReq := LoginRequest{
			Email:    r.Email,
			Password: r.Password,
		}
		return validation.Validate(validateReq)

	case *ListUsersReq:
		// Apply defaults
		if r.Page == 0 {
			r.Page = 1
		}
		if r.Size == 0 {
			r.Size = 10
		}
		if r.SortBy == "" {
			r.SortBy = "created_at"
		}
		if r.SortOrder == "" {
			r.SortOrder = "desc"
		}

		validateReq := ListUsersRequest{
			Page:      r.Page,
			Size:      r.Size,
			Search:    r.Search,
			SortBy:    r.SortBy,
			SortOrder: r.SortOrder,
		}
		return validation.Validate(validateReq)

	case *UpdateUserReq:
		validateReq := UpdateUserRequest{
			Name:   r.Name,
			Phone:  r.Phone,
			Status: r.Status,
		}
		return validation.Validate(validateReq)
	}

	return nil
}
