// Command protoc-gen-fiber is a protoc/buf plugin that generates Go Fiber route
// registration from the grst.route options declared on each RPC in a .proto
// file. It lets the proto contract be the single source of truth for a
// service's REST surface: method, path, path/query/body binding, auth policy,
// and per-route rate limiting.
//
// For a service Foo it emits, into <file>_fiber.pb.go:
//
//   - RegisterFooRoutes(router fiber.Router, srv FooServer, validator middleware.TokenValidator)
//   - FooAuthConfig — a map of gRPC full-method name to auth policy, for the
//     gRPC auth interceptor (so gRPC and REST share one auth declaration).
package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	grst "go-grst-boilerplate/handler/grpc/grst"
)

// Import paths referenced by generated code.
const (
	fiberPkg      = protogen.GoImportPath("github.com/gofiber/fiber/v2")
	middlewarePkg = protogen.GoImportPath("go-grst-boilerplate/pkg/middleware")
	responsePkg   = protogen.GoImportPath("go-grst-boilerplate/pkg/response")
	errorsPkg     = protogen.GoImportPath("go-grst-boilerplate/pkg/errors")
	protoPkg      = protogen.GoImportPath("google.golang.org/protobuf/proto")
	contextPkg    = protogen.GoImportPath("context")
	timePkg       = protogen.GoImportPath("time")
	emptyFullName = "google.protobuf.Empty"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(1) // FEATURE_PROTO3_OPTIONAL
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if !fileHasRoutes(f) {
				continue
			}
			if err := generateFile(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

// routeFor returns the grst.route option attached to a method, or nil.
func routeFor(m *protogen.Method) *grst.Route {
	opts := m.Desc.Options()
	if opts == nil {
		return nil
	}
	ext := proto.GetExtension(opts, grst.E_Route)
	r, _ := ext.(*grst.Route)
	if r == nil || r.GetPath() == "" {
		return nil
	}
	return r
}

func fileHasRoutes(f *protogen.File) bool {
	for _, svc := range f.Services {
		for _, m := range svc.Methods {
			if routeFor(m) != nil {
				return true
			}
		}
	}
	return false
}

func generateFile(gen *protogen.Plugin, f *protogen.File) error {
	filename := f.GeneratedFilenamePrefix + "_fiber.pb.go"
	g := gen.NewGeneratedFile(filename, f.GoImportPath)

	g.P("// Code generated by protoc-gen-fiber. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	for _, svc := range f.Services {
		if err := generateService(g, svc); err != nil {
			return err
		}
	}
	return nil
}

func generateService(g *protogen.GeneratedFile, svc *protogen.Service) error {
	// Collect methods that declare a route, in declaration order.
	type routed struct {
		m *protogen.Method
		r *grst.Route
	}
	var routes []routed
	for _, m := range svc.Methods {
		if r := routeFor(m); r != nil {
			routes = append(routes, routed{m, r})
		}
	}
	if len(routes) == 0 {
		return nil
	}

	svcName := svc.GoName
	serverType := svcName + "Server"
	fullName := string(svc.Desc.FullName())

	fiberRouter := g.QualifiedGoIdent(fiberPkg.Ident("Router"))
	fiberHandler := g.QualifiedGoIdent(fiberPkg.Ident("Handler"))
	fiberCtx := g.QualifiedGoIdent(fiberPkg.Ident("Ctx"))
	tokenValidator := g.QualifiedGoIdent(middlewarePkg.Ident("TokenValidator"))
	authConfig := g.QualifiedGoIdent(middlewarePkg.Ident("AuthConfig"))

	// --- gRPC auth map (shared with the gRPC interceptor) ---
	g.P("// ", svcName, "AuthConfig maps each gRPC full-method name to its auth policy.")
	g.P("// It is derived from the grst.route auth options and consumed by the gRPC")
	g.P("// auth interceptor so gRPC and REST enforce the same rules.")
	g.P("var ", svcName, "AuthConfig = map[string]", authConfig, "{")
	for _, rt := range routes {
		method := "/" + fullName + "/" + string(rt.m.Desc.Name())
		g.P("\t", strconv(method), ": ", authConfigLiteral(g, rt.r), ",")
	}
	g.P("}")
	g.P()

	// --- Route registration ---
	g.P("// Register", svcName, "Routes registers all REST routes for ", svcName, " on router,")
	g.P("// applying per-route auth and rate limiting declared in the proto.")
	g.P("func Register", svcName, "Routes(router ", fiberRouter, ", srv ", serverType, ", validator ", tokenValidator, ") {")
	for _, rt := range routes {
		verb := fiberVerb(rt.r.GetMethod())
		path := toFiberPath(rt.r.GetPath())
		var mws []string
		if rl := rt.r.GetRateLimit(); rl != nil && rl.GetMax() > 0 {
			mws = append(mws, fmt.Sprintf("_%s_rateLimit(%d, %d*%s)",
				svcName, rl.GetMax(), rl.GetWindowSeconds(), g.QualifiedGoIdent(timePkg.Ident("Second"))))
		}
		if needAuth(rt.r) {
			mws = append(mws, fmt.Sprintf("%s(validator, %s)",
				g.QualifiedGoIdent(middlewarePkg.Ident("AuthMiddleware")), authConfigLiteral(g, rt.r)))
		}
		handler := fmt.Sprintf("_%s_%s(srv)", svcName, rt.m.GoName)
		args := append([]string{strconv(path)}, append(mws, handler)...)
		g.P("\trouter.", verb, "(", strings.Join(args, ", "), ")")
	}
	g.P("}")
	g.P()

	// --- Per-method handler constructors ---
	for _, rt := range routes {
		generateHandler(g, svcName, rt.m, rt.r)
	}

	// --- Shared helpers (one set per service) ---
	g.P("// _", svcName, "_ctx propagates the auth context (if present) into the")
	g.P("// request context passed to the handler.")
	g.P("func _", svcName, "_ctx(c *", fiberCtx, ") ", g.QualifiedGoIdent(contextPkg.Ident("Context")), " {")
	g.P("\tctx := c.UserContext()")
	g.P("\tif ac, ok := ", g.QualifiedGoIdent(middlewarePkg.Ident("GetAuthContext")), "(c); ok {")
	g.P("\t\tctx = ", g.QualifiedGoIdent(middlewarePkg.Ident("WithAuthContext")), "(ctx, ac)")
	g.P("\t}")
	g.P("\treturn ctx")
	g.P("}")
	g.P()

	g.P("// _", svcName, "_error renders a handler error: AppError values keep their")
	g.P("// status/message; anything else becomes a sanitized 500.")
	g.P("func _", svcName, "_error(c *", fiberCtx, ", err error) error {")
	g.P("\tif appErr, ok := err.(*", g.QualifiedGoIdent(errorsPkg.Ident("AppError")), "); ok {")
	g.P("\t\treturn appErr.FiberError(c)")
	g.P("\t}")
	g.P("\treturn ", g.QualifiedGoIdent(responsePkg.Ident("InternalError")), "(c, 500, \"internal server error\")")
	g.P("}")
	g.P()

	g.P("// _", svcName, "_rateLimit builds a fixed-window per-IP limiter middleware.")
	g.P("func _", svcName, "_rateLimit(max int, window ", g.QualifiedGoIdent(timePkg.Ident("Duration")), ") ", fiberHandler, " {")
	g.P("\tcfg := ", g.QualifiedGoIdent(middlewarePkg.Ident("DefaultRateLimitConfig")), "()")
	g.P("\tcfg.Max = max")
	g.P("\tcfg.Duration = window")
	g.P("\treturn ", g.QualifiedGoIdent(middlewarePkg.Ident("RateLimitMiddleware")), "(cfg)")
	g.P("}")
	g.P()

	return nil
}

func generateHandler(g *protogen.GeneratedFile, svcName string, m *protogen.Method, r *grst.Route) {
	fiberCtx := g.QualifiedGoIdent(fiberPkg.Ident("Ctx"))
	fiberHandler := g.QualifiedGoIdent(fiberPkg.Ident("Handler"))
	reqType := g.QualifiedGoIdent(m.Input.GoIdent)
	isEmpty := string(m.Input.Desc.FullName()) == emptyFullName

	g.P("func _", svcName, "_", m.GoName, "(srv ", svcName, "Server) ", fiberHandler, " {")
	g.P("\treturn func(c *", fiberCtx, ") error {")

	if isEmpty {
		g.P("\t\treq := &", reqType, "{}")
	} else {
		g.P("\t\tvar req ", reqType)
		// Body binding first, so path params take precedence over body values.
		if r.GetBody() {
			g.P("\t\tif err := c.BodyParser(&req); err != nil {")
			g.P("\t\t\treturn ", g.QualifiedGoIdent(responsePkg.Ident("BadRequest")), "(c, 400, \"invalid request body\")")
			g.P("\t\t}")
		}
		pathParams := bindPathParams(g, m, r)
		// Query binding for GET requests: any scalar field not bound via a path
		// param is populated from the query string (json_name as the key).
		if strings.EqualFold(r.GetMethod(), "GET") {
			bindQueryParams(g, m, pathParams)
		}
	}

	reqArg := "req"
	if !isEmpty {
		reqArg = "&req"
	}
	g.P("\t\tctx := _", svcName, "_ctx(c)")
	g.P("\t\tres, err := srv.", m.GoName, "(ctx, ", reqArg, ")")
	g.P("\t\tif err != nil {")
	g.P("\t\t\treturn _", svcName, "_error(c, err)")
	g.P("\t\t}")
	writeResponse(g, m, r)
	g.P("\t}")
	g.P("}")
	g.P()
}

// bindPathParams emits assignments from Fiber path params to request fields and
// returns the set of field json names it consumed.
func bindPathParams(g *protogen.GeneratedFile, m *protogen.Method, r *grst.Route) map[string]bool {
	consumed := map[string]bool{}
	for _, name := range pathParamNames(r.GetPath()) {
		field := findField(m.Input, name)
		if field == nil {
			continue
		}
		consumed[field.Desc.JSONName()] = true
		g.P("\t\treq.", field.GoName, " = c.Params(", strconv(name), ")")
	}
	return consumed
}

func bindQueryParams(g *protogen.GeneratedFile, m *protogen.Method, skip map[string]bool) {
	for _, field := range m.Input.Fields {
		if field.Desc.IsList() || field.Desc.IsMap() || field.Desc.Message() != nil {
			continue
		}
		jsonName := field.Desc.JSONName()
		if skip[jsonName] {
			continue
		}
		switch field.Desc.Kind() {
		case protoreflect.StringKind:
			g.P("\t\treq.", field.GoName, " = c.Query(", strconv(jsonName), ")")
		case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
			g.P("\t\treq.", field.GoName, " = int32(c.QueryInt(", strconv(jsonName), ", 0))")
		case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
			g.P("\t\treq.", field.GoName, " = int64(c.QueryInt(", strconv(jsonName), ", 0))")
		case protoreflect.BoolKind:
			g.P("\t\treq.", field.GoName, " = c.QueryBool(", strconv(jsonName), ")")
		}
	}
}

func writeResponse(g *protogen.GeneratedFile, m *protogen.Method, r *grst.Route) {
	switch r.GetResponse() {
	case grst.ResponseStyle_RESPONSE_STYLE_CREATED:
		g.P("\t\treturn ", g.QualifiedGoIdent(responsePkg.Ident("CreatedProto")), "(c, res)")
	case grst.ResponseStyle_RESPONSE_STYLE_LIST:
		listField, metaField := listFields(m.Output)
		if listField == nil {
			// Fall back to a plain envelope if the message is not list-shaped.
			g.P("\t\treturn ", g.QualifiedGoIdent(responsePkg.Ident("SuccessProto")), "(c, res)")
			return
		}
		protoMsg := g.QualifiedGoIdent(protoPkg.Ident("Message"))
		g.P("\t\titems := make([]", protoMsg, ", len(res.", listField.GoName, "))")
		g.P("\t\tfor i, m := range res.", listField.GoName, " {")
		g.P("\t\t\titems[i] = m")
		g.P("\t\t}")
		metaArg := "nil"
		if metaField != nil {
			metaArg = "res." + metaField.GoName
		}
		g.P("\t\treturn ", g.QualifiedGoIdent(responsePkg.Ident("SuccessProtoList")), "(c, items, ", metaArg, ")")
	default:
		g.P("\t\treturn ", g.QualifiedGoIdent(responsePkg.Ident("SuccessProto")), "(c, res)")
	}
}

// --- helpers ---

func needAuth(r *grst.Route) bool {
	a := r.GetAuth()
	return a != nil && (a.GetRequired() || len(a.GetRoles()) > 0)
}

func authConfigLiteral(g *protogen.GeneratedFile, r *grst.Route) string {
	authConfig := g.QualifiedGoIdent(middlewarePkg.Ident("AuthConfig"))
	a := r.GetAuth()
	if a == nil || (!a.GetRequired() && len(a.GetRoles()) == 0) {
		return authConfig + "{NeedAuth: false, AllowedRoles: nil}"
	}
	if len(a.GetRoles()) == 0 {
		return authConfig + "{NeedAuth: true, AllowedRoles: nil}"
	}
	quoted := make([]string, len(a.GetRoles()))
	for i, role := range a.GetRoles() {
		quoted[i] = strconv(role)
	}
	return fmt.Sprintf("%s{NeedAuth: true, AllowedRoles: []string{%s}}", authConfig, strings.Join(quoted, ", "))
}

// listFields returns the single repeated field (the list payload) and the first
// singular message field (the pagination meta), if present.
func listFields(msg *protogen.Message) (list, meta *protogen.Field) {
	for _, f := range msg.Fields {
		if f.Desc.IsList() && f.Desc.Message() != nil && list == nil {
			list = f
			continue
		}
		if !f.Desc.IsList() && f.Desc.Message() != nil && meta == nil {
			meta = f
		}
	}
	return list, meta
}

func findField(msg *protogen.Message, jsonOrName string) *protogen.Field {
	for _, f := range msg.Fields {
		if f.Desc.JSONName() == jsonOrName || string(f.Desc.Name()) == jsonOrName {
			return f
		}
	}
	return nil
}

func pathParamNames(path string) []string {
	var names []string
	for {
		open := strings.IndexByte(path, '{')
		if open < 0 {
			break
		}
		close := strings.IndexByte(path[open:], '}')
		if close < 0 {
			break
		}
		names = append(names, path[open+1:open+close])
		path = path[open+close+1:]
	}
	return names
}

// toFiberPath converts {name} path segments to Fiber's :name syntax.
func toFiberPath(path string) string {
	var b strings.Builder
	for i := 0; i < len(path); i++ {
		if path[i] == '{' {
			end := strings.IndexByte(path[i:], '}')
			if end < 0 {
				b.WriteString(path[i:])
				break
			}
			b.WriteByte(':')
			b.WriteString(path[i+1 : i+end])
			i += end
			continue
		}
		b.WriteByte(path[i])
	}
	return b.String()
}

func fiberVerb(method string) string {
	switch strings.ToUpper(method) {
	case "GET":
		return "Get"
	case "POST":
		return "Post"
	case "PUT":
		return "Put"
	case "PATCH":
		return "Patch"
	case "DELETE":
		return "Delete"
	default:
		return "Get"
	}
}

// strconv quotes a string as a Go literal.
func strconv(s string) string {
	return fmt.Sprintf("%q", s)
}
