// Code generated by protoc-gen-fiber. DO NOT EDIT.
// source: user/user.proto

package user

import (
	context "context"
	v2 "github.com/gofiber/fiber/v2"
	errors "go-grst-boilerplate/pkg/errors"
	middleware "go-grst-boilerplate/pkg/middleware"
	response "go-grst-boilerplate/pkg/response"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	time "time"
)

// UserApiAuthConfig maps each gRPC full-method name to its auth policy.
// It is derived from the grst.route auth options and consumed by the gRPC
// auth interceptor so gRPC and REST enforce the same rules.
var UserApiAuthConfig = map[string]middleware.AuthConfig{
	"/user.UserApi/Register":     middleware.AuthConfig{NeedAuth: false, AllowedRoles: nil},
	"/user.UserApi/Login":        middleware.AuthConfig{NeedAuth: false, AllowedRoles: nil},
	"/user.UserApi/RefreshToken": middleware.AuthConfig{NeedAuth: true, AllowedRoles: nil},
	"/user.UserApi/GetMe":        middleware.AuthConfig{NeedAuth: true, AllowedRoles: nil},
	"/user.UserApi/Logout":       middleware.AuthConfig{NeedAuth: true, AllowedRoles: nil},
	"/user.UserApi/ListUsers":    middleware.AuthConfig{NeedAuth: true, AllowedRoles: []string{"admin", "superadmin"}},
	"/user.UserApi/GetUser":      middleware.AuthConfig{NeedAuth: true, AllowedRoles: []string{"admin", "superadmin"}},
	"/user.UserApi/UpdateUser":   middleware.AuthConfig{NeedAuth: true, AllowedRoles: []string{"admin", "superadmin"}},
	"/user.UserApi/DeleteUser":   middleware.AuthConfig{NeedAuth: true, AllowedRoles: []string{"admin", "superadmin"}},
}

// RegisterUserApiRoutes registers all REST routes for UserApi on router,
// applying per-route auth and rate limiting declared in the proto.
func RegisterUserApiRoutes(router v2.Router, srv UserApiServer, validator middleware.TokenValidator) {
	router.Post("/api/v1/auth/register", _UserApi_rateLimit(10, 60*time.Second), _UserApi_Register(srv))
	router.Post("/api/v1/auth/login", _UserApi_rateLimit(10, 60*time.Second), _UserApi_Login(srv))
	router.Post("/api/v1/auth/refresh", middleware.AuthMiddleware(validator, middleware.AuthConfig{NeedAuth: true, AllowedRoles: nil}), _UserApi_RefreshToken(srv))
	router.Get("/api/v1/auth/me", middleware.AuthMiddleware(validator, middleware.AuthConfig{NeedAuth: true, AllowedRoles: nil}), _UserApi_GetMe(srv))
	router.Post("/api/v1/auth/logout", middleware.AuthMiddleware(validator, middleware.AuthConfig{NeedAuth: true, AllowedRoles: nil}), _UserApi_Logout(srv))
	router.Get("/api/v1/users", middleware.AuthMiddleware(validator, middleware.AuthConfig{NeedAuth: true, AllowedRoles: []string{"admin", "superadmin"}}), _UserApi_ListUsers(srv))
	router.Get("/api/v1/users/:id", middleware.AuthMiddleware(validator, middleware.AuthConfig{NeedAuth: true, AllowedRoles: []string{"admin", "superadmin"}}), _UserApi_GetUser(srv))
	router.Put("/api/v1/users/:id", middleware.AuthMiddleware(validator, middleware.AuthConfig{NeedAuth: true, AllowedRoles: []string{"admin", "superadmin"}}), _UserApi_UpdateUser(srv))
	router.Delete("/api/v1/users/:id", middleware.AuthMiddleware(validator, middleware.AuthConfig{NeedAuth: true, AllowedRoles: []string{"admin", "superadmin"}}), _UserApi_DeleteUser(srv))
}

func _UserApi_Register(srv UserApiServer) v2.Handler {
	return func(c *v2.Ctx) error {
		var req RegisterReq
		if err := c.BodyParser(&req); err != nil {
			return response.BadRequest(c, 400, "invalid request body")
		}
		ctx := _UserApi_ctx(c)
		res, err := srv.Register(ctx, &req)
		if err != nil {
			return _UserApi_error(c, err)
		}
		return response.CreatedProto(c, res)
	}
}

func _UserApi_Login(srv UserApiServer) v2.Handler {
	return func(c *v2.Ctx) error {
		var req LoginReq
		if err := c.BodyParser(&req); err != nil {
			return response.BadRequest(c, 400, "invalid request body")
		}
		ctx := _UserApi_ctx(c)
		res, err := srv.Login(ctx, &req)
		if err != nil {
			return _UserApi_error(c, err)
		}
		return response.SuccessProto(c, res)
	}
}

func _UserApi_RefreshToken(srv UserApiServer) v2.Handler {
	return func(c *v2.Ctx) error {
		var req RefreshTokenReq
		ctx := _UserApi_ctx(c)
		res, err := srv.RefreshToken(ctx, &req)
		if err != nil {
			return _UserApi_error(c, err)
		}
		return response.SuccessProto(c, res)
	}
}

func _UserApi_GetMe(srv UserApiServer) v2.Handler {
	return func(c *v2.Ctx) error {
		req := &emptypb.Empty{}
		ctx := _UserApi_ctx(c)
		res, err := srv.GetMe(ctx, req)
		if err != nil {
			return _UserApi_error(c, err)
		}
		return response.SuccessProto(c, res)
	}
}

func _UserApi_Logout(srv UserApiServer) v2.Handler {
	return func(c *v2.Ctx) error {
		req := &emptypb.Empty{}
		ctx := _UserApi_ctx(c)
		res, err := srv.Logout(ctx, req)
		if err != nil {
			return _UserApi_error(c, err)
		}
		return response.SuccessProto(c, res)
	}
}

func _UserApi_ListUsers(srv UserApiServer) v2.Handler {
	return func(c *v2.Ctx) error {
		var req ListUsersReq
		req.Page = int32(c.QueryInt("page", 0))
		req.Size = int32(c.QueryInt("size", 0))
		req.Search = c.Query("search")
		req.SortBy = c.Query("sortBy")
		req.SortOrder = c.Query("sortOrder")
		ctx := _UserApi_ctx(c)
		res, err := srv.ListUsers(ctx, &req)
		if err != nil {
			return _UserApi_error(c, err)
		}
		items := make([]proto.Message, len(res.Users))
		for i, m := range res.Users {
			items[i] = m
		}
		return response.SuccessProtoList(c, items, res.Pagination)
	}
}

func _UserApi_GetUser(srv UserApiServer) v2.Handler {
	return func(c *v2.Ctx) error {
		var req GetUserReq
		req.Id = c.Params("id")
		ctx := _UserApi_ctx(c)
		res, err := srv.GetUser(ctx, &req)
		if err != nil {
			return _UserApi_error(c, err)
		}
		return response.SuccessProto(c, res)
	}
}

func _UserApi_UpdateUser(srv UserApiServer) v2.Handler {
	return func(c *v2.Ctx) error {
		var req UpdateUserReq
		if err := c.BodyParser(&req); err != nil {
			return response.BadRequest(c, 400, "invalid request body")
		}
		req.Id = c.Params("id")
		ctx := _UserApi_ctx(c)
		res, err := srv.UpdateUser(ctx, &req)
		if err != nil {
			return _UserApi_error(c, err)
		}
		return response.SuccessProto(c, res)
	}
}

func _UserApi_DeleteUser(srv UserApiServer) v2.Handler {
	return func(c *v2.Ctx) error {
		var req DeleteUserReq
		req.Id = c.Params("id")
		ctx := _UserApi_ctx(c)
		res, err := srv.DeleteUser(ctx, &req)
		if err != nil {
			return _UserApi_error(c, err)
		}
		return response.SuccessProto(c, res)
	}
}

// _UserApi_ctx propagates the auth context (if present) into the
// request context passed to the handler.
func _UserApi_ctx(c *v2.Ctx) context.Context {
	ctx := c.UserContext()
	if ac, ok := middleware.GetAuthContext(c); ok {
		ctx = middleware.WithAuthContext(ctx, ac)
	}
	return ctx
}

// _UserApi_error renders a handler error: AppError values keep their
// status/message; anything else becomes a sanitized 500.
func _UserApi_error(c *v2.Ctx, err error) error {
	if appErr, ok := err.(*errors.AppError); ok {
		return appErr.FiberError(c)
	}
	return response.InternalError(c, 500, "internal server error")
}

// _UserApi_rateLimit builds a fixed-window per-IP limiter middleware.
func _UserApi_rateLimit(max int, window time.Duration) v2.Handler {
	cfg := middleware.DefaultRateLimitConfig()
	cfg.Max = max
	cfg.Duration = window
	return middleware.RateLimitMiddleware(cfg)
}
