// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a manual stub - run `make proto` to generate actual code

package user

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
	Phone    string `json:"phone"`
}

type RegisterRes struct {
	Id    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginRes struct {
	Token string       `json:"token"`
	User  *UserProfile `json:"user"`
}

type RefreshTokenReq struct {
	Token string `json:"token"`
}

type RefreshTokenRes struct {
	Token string `json:"token"`
}

type LogoutRes struct {
	Message string `json:"message"`
}

type UserProfile struct {
	Id        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	Phone     string `json:"phone"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type ListUsersReq struct {
	Page      int32  `json:"page"`
	Size      int32  `json:"size"`
	Search    string `json:"search"`
	SortBy    string `json:"sortBy"`
	SortOrder string `json:"sortOrder"`
}

type ListUsersRes struct {
	Users      []*UserProfile `json:"users"`
	Pagination *Pagination    `json:"pagination"`
}

type Pagination struct {
	Page       int32 `json:"page"`
	Size       int32 `json:"size"`
	Total      int64 `json:"total"`
	TotalPages int32 `json:"totalPages"`
}

type GetUserReq struct {
	Id string `json:"id"`
}

type UpdateUserReq struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Status string `json:"status"`
}

type DeleteUserReq struct {
	Id string `json:"id"`
}

type DeleteUserRes struct {
	Message string `json:"message"`
}
