// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a manual stub - run `make proto` to generate actual code

package user

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

type UserApiServer interface {
	Register(context.Context, *RegisterReq) (*RegisterRes, error)
	Login(context.Context, *LoginReq) (*LoginRes, error)
	GetProfile(context.Context, *emptypb.Empty) (*UserProfile, error)
	ListAllUsers(context.Context, *ListUsersReq) (*ListUsersRes, error)
	GetMyPayslip(context.Context, *GetPayslipReq) (*Payslip, error)
}

type UnimplementedUserApiServer struct{}

func (UnimplementedUserApiServer) Register(context.Context, *RegisterReq) (*RegisterRes, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) Login(context.Context, *LoginReq) (*LoginRes, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) GetProfile(context.Context, *emptypb.Empty) (*UserProfile, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) ListAllUsers(context.Context, *ListUsersReq) (*ListUsersRes, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) GetMyPayslip(context.Context, *GetPayslipReq) (*Payslip, error) {
	return nil, nil
}

type UnsafeUserApiServer interface {
	mustEmbedUnimplementedUserApiServer()
}

func RegisterUserApiServer(s *grpc.Server, srv UserApiServer) {
	// Registration logic - implement with actual generated code
}
