// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a manual stub - run `make proto` to generate actual code

package user

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

type UserApiServer interface {
	Register(context.Context, *RegisterReq) (*RegisterRes, error)
	Login(context.Context, *LoginReq) (*LoginRes, error)
	RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenRes, error)
	GetMe(context.Context, *emptypb.Empty) (*UserProfile, error)
	Logout(context.Context, *emptypb.Empty) (*LogoutRes, error)
	ListUsers(context.Context, *ListUsersReq) (*ListUsersRes, error)
	GetUser(context.Context, *GetUserReq) (*UserProfile, error)
	UpdateUser(context.Context, *UpdateUserReq) (*UserProfile, error)
	DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserRes, error)
}

type UnimplementedUserApiServer struct{}

func (UnimplementedUserApiServer) Register(context.Context, *RegisterReq) (*RegisterRes, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) Login(context.Context, *LoginReq) (*LoginRes, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenRes, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) GetMe(context.Context, *emptypb.Empty) (*UserProfile, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) Logout(context.Context, *emptypb.Empty) (*LogoutRes, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) ListUsers(context.Context, *ListUsersReq) (*ListUsersRes, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) GetUser(context.Context, *GetUserReq) (*UserProfile, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) UpdateUser(context.Context, *UpdateUserReq) (*UserProfile, error) {
	return nil, nil
}

func (UnimplementedUserApiServer) DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserRes, error) {
	return nil, nil
}

type UnsafeUserApiServer interface {
	mustEmbedUnimplementedUserApiServer()
}

func RegisterUserApiServer(s *grpc.Server, srv UserApiServer) {
	// Registration logic - implement with actual generated code
}
